create table home(
    id          int8 generated by default as identity,
    description varchar(2048),
    location    varchar(2048),
    price       numeric(19, 2),
    sleep_place int4 not null,
    primary key (id)
)