create table car
(
    id          int8 generated by default as identity,
    description varchar(2048),
    route_from   varchar(255),
    route_to     varchar(255),
    date        date,
    price       numeric(19, 2),
    primary key (id)
)